-- Spoonacular product image URLs
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/pineapple-juice.jpg' WHERE name = 'Apple Juice';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/apple.jpg' WHERE name = 'Apples';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/white-powder.jpg' WHERE name = 'Baking Powder';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/bananas.jpg' WHERE name = 'Bananas';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/rice-white-long-grain-or-basmatii-cooked.jpg' WHERE name = 'Basmati Rice';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/barbecue-sauce.jpg' WHERE name = 'BBQ Sauce';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/fresh-ground-beef.jpg' WHERE name = 'Beef Mince';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/top-sirloin-steak.jpg' WHERE name = 'Beef Steak';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/bell-pepper-orange.png' WHERE name = 'Bell Peppers';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/salt-and-pepper.jpg' WHERE name = 'Black Pepper';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/tea-bags.jpg' WHERE name = 'Black Tea Bags';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/dark-brown-sugar.png' WHERE name = 'Brown Sugar';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/black-beans.jpg' WHERE name = 'Canned Beans';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/corn.png' WHERE name = 'Canned Corn';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/tomatoes-canned.png' WHERE name = 'Canned Tomatoes';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/canned-tuna.png' WHERE name = 'Canned Tuna';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/sliced-carrot.png' WHERE name = 'Carrots';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/cheddar-cheese.png' WHERE name = 'Cheddar Cheese';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/cheesecake-isolated.jpg' WHERE name = 'Cheesecake';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/deli-turkey.jpg' WHERE name = 'Chicken Breast';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chicken-drumsticks.jpg' WHERE name = 'Chicken Drumsticks';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chicken-thighs.png' WHERE name = 'Chicken Thighs';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chicken-wings.png' WHERE name = 'Chicken Wings';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/red-pepper-flakes.jpg' WHERE name = 'Chili Flakes';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chocolate-cake.jpg' WHERE name = 'Chocolate Cake';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chocolate-wafer-cookies.jpg' WHERE name = 'Chocolate Cookies';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chocolate-ice-cream.png' WHERE name = 'Chocolate Ice Cream';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/chocolate-wafer-cookies.jpg' WHERE name = 'Chocolate Wafers';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/cinnamon-roll.jpg' WHERE name = 'Cinnamon Rolls';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/cod-fillet.jpg' WHERE name = 'Cod Fillet';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/coca-cola.png' WHERE name = 'Cola';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/croissants.jpg' WHERE name = 'Croissants';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/cucumber.jpg' WHERE name = 'Cucumbers';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/Edam-cheese.jpg' WHERE name = 'Edam Cheese';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/mixed-vegetables.png' WHERE name = 'Frozen Mixed Veg';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/pizza-isolated.png' WHERE name = 'Frozen Pizza';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/spinach-frozen.jpg' WHERE name = 'Frozen Spinach';
UPDATE products SET image_url = 'https://spoonacular.com/cdn/ingredients_400x400/garlic-powder.png' WHERE name = 'Garlic Powder';
